name: ProcessCraft
author: facered
main: cn.gionrose.facered.ProcessCraft
api-version: 1.20
version: 1.0.0
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.8.10
  - com.zaxxer:HikariCP:5.0.1
#  - mysql:mysql-connector-java:8.0.33
depend: [PlayerPoints, PlaceholderAPI, Vault]

commands:
  processcraft:
    usage: /<command> <action> <playerName> <taskName>
    permission: processcraft.use